from django.contrib.auth import authenticate
from rest_framework import serializers
from dj_rest_auth.serializers import PasswordResetSerializer
from dj_rest_auth.registration.serializers import RegisterSerializer
from django.conf import settings
from .forms import CustomPasswordResetForm


class CustomRegisterSerializer(RegisterSerializer):
    """
    Custom registration serializer that only requires email and password
    Username will be auto-generated by the adapter
    """
    # Remove username requirement
    username = None
    
    def get_cleaned_data(self):
        """
        Return cleaned data without username
        The adapter will auto-generate it
        """
        return {
            'email': self.validated_data.get('email', ''),
            'password1': self.validated_data.get('password1', ''),
            'password2': self.validated_data.get('password2', ''),
        }


class CustomPasswordResetSerializer(PasswordResetSerializer):
    """
    Custom password reset serializer to use frontend URL
    """
    @property
    def password_reset_form_class(self):
        return CustomPasswordResetForm
    
    def get_email_options(self):
        """Override to use custom email templates"""
        return {
            'email_template_name': 'emails/password_reset/password_reset_message.txt',
            'html_email_template_name': 'emails/password_reset/password_reset_message.html',
            'subject_template_name': 'emails/password_reset/password_reset_subject.txt',
        }


class CustomLoginSerializer(serializers.Serializer):
    """
    Custom login serializer that accepts 'email' and 'password'
    """
    email = serializers.EmailField(required=True)
    password = serializers.CharField(
        required=True,
        style={'input_type': 'password'},
        write_only=True
    )
    
    def validate(self, attrs):
        email = attrs.get('email')
        password = attrs.get('password')
        
        if email and password:
            # Authenticate using email as username
            user = authenticate(
                request=self.context.get('request'),
                username=email,
                password=password
            )
            
            if not user:
                msg = 'Unable to log in with provided credentials.'
                raise serializers.ValidationError(msg, code='authorization')
            
            if not user.is_active:
                msg = 'User account is disabled.'
                raise serializers.ValidationError(msg, code='authorization')
                
        else:
            msg = 'Must include "email" and "password".'
            raise serializers.ValidationError(msg, code='authorization')
        
        attrs['user'] = user
        return attrs


class DeleteAccountSerializer(serializers.Serializer):
    """
    Serializer for account deletion with options
    """
    delete_classifications = serializers.BooleanField(
        default=False,
        required=False,
        help_text="If true, delete all classifications. If false, preserve classifications anonymously."
    )
    confirm = serializers.BooleanField(
        required=True,
        help_text="Must be true to confirm account deletion"
    )
    
    def validate_confirm(self, value):
        if not value:
            raise serializers.ValidationError("You must confirm account deletion by setting 'confirm' to true")
        return value
