# Generated by Django 4.2.7 on 2025-11-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abstract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('authors', models.TextField()),
                ('abstract_text', models.TextField()),
                ('keywords', models.TextField(blank=True)),
                ('doi', models.CharField(db_index=True, max_length=200, unique=True)),
                ('publication_year', models.IntegerField(blank=True, null=True)),
                ('journal', models.CharField(blank=True, max_length=500)),
                ('url', models.URLField(blank=True, max_length=500)),
                ('required_classifications', models.IntegerField(default=5)),
                ('current_classifications_count', models.IntegerField(default=0)),
                ('difficulty_score', models.FloatField(default=0.0)),
                ('consensus_reached', models.BooleanField(default=False)),
                ('is_gold_standard', models.BooleanField(default=False)),
                ('gold_classifications_complete', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Abstract',
                'verbose_name_plural': 'Abstracts',
                'ordering': ['current_classifications_count', '-created_at'],
                'indexes': [models.Index(fields=['doi'], name='abstracts_a_doi_183865_idx'), models.Index(fields=['is_gold_standard', 'gold_classifications_complete'], name='abstracts_a_is_gold_ebe898_idx'), models.Index(fields=['current_classifications_count', 'consensus_reached'], name='abstracts_a_current_8c91f1_idx')],
            },
        ),
    ]
