# Generated by Django 4.2.7 on 2025-11-12 16:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstracts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstract',
            name='last_shown_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='abstract',
            name='publication_type',
            field=models.CharField(choices=[('J', 'Journal Article'), ('C', 'Conference Paper'), ('B', 'Book Chapter'), ('S', 'Series')], db_index=True, default='J', max_length=1),
        ),
        migrations.AddField(
            model_name='abstract',
            name='times_shown',
            field=models.IntegerField(default=0, help_text='Number of times shown to users'),
        ),
        migrations.AlterField(
            model_name='abstract',
            name='consensus_reached',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='abstract',
            name='current_classifications_count',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='abstract',
            name='difficulty_score',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='abstract',
            name='doi',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='abstract',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='abstract',
            name='is_gold_standard',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='abstract',
            name='required_classifications',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddIndex(
            model_name='abstract',
            index=models.Index(fields=['is_active', 'is_gold_standard', 'current_classifications_count'], name='abstracts_a_is_acti_270903_idx'),
        ),
        migrations.AddIndex(
            model_name='abstract',
            index=models.Index(fields=['publication_type', 'publication_year'], name='abstracts_a_publica_8f7bdf_idx'),
        ),
        migrations.AddConstraint(
            model_name='abstract',
            constraint=models.CheckConstraint(check=models.Q(('current_classifications_count__gte', 0)), name='positive_classification_count'),
        ),
        migrations.AddConstraint(
            model_name='abstract',
            constraint=models.CheckConstraint(check=models.Q(('required_classifications__gte', 1)), name='minimum_required_classifications'),
        ),
    ]
