# Generated by Django 4.2.7 on 2025-11-12 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstracts', '0002_abstract_last_shown_at_abstract_publication_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstract',
            name='affiliations',
            field=models.TextField(blank=True, help_text='Author addresses/affiliations (C1 field from WoS)'),
        ),
        migrations.AddField(
            model_name='abstract',
            name='research_areas',
            field=models.TextField(blank=True, help_text='Research Areas (SC field from WoS)'),
        ),
        migrations.AddField(
            model_name='abstract',
            name='times_cited',
            field=models.IntegerField(db_index=True, default=0, help_text='Number of times cited (TC field from WoS)'),
        ),
        migrations.AddField(
            model_name='abstract',
            name='wos_categories',
            field=models.TextField(blank=True, help_text='Web of Science Categories (WC field from WoS)'),
        ),
    ]
