# Generated by Django 4.2.7 on 2025-11-12 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('abstracts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_gold_user', models.BooleanField(default=False)),
                ('reliability_score', models.FloatField(default=0.0)),
                ('total_classifications', models.IntegerField(default=0)),
                ('agreement_with_gold', models.FloatField(default=0.0)),
                ('completed_training', models.BooleanField(default=False)),
                ('training_score', models.FloatField(default=0.0)),
                ('training_attempts', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=1)),
                ('badges', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='classification_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='GoldStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_classification', models.CharField(max_length=50)),
                ('main_agreement_score', models.FloatField(help_text='Agreement level (0-1)')),
                ('meta_aspects', models.JSONField(blank=True, default=list)),
                ('meta_agreement_score', models.FloatField(default=0.0)),
                ('infrastructure_mentions', models.JSONField(blank=True, default=list, help_text='List of infrastructure mentions')),
                ('num_gold_classifications', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('abstract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gold_standards', to='abstracts.abstract')),
            ],
            options={
                'verbose_name': 'Gold Standard',
                'verbose_name_plural': 'Gold Standards',
            },
        ),
        migrations.CreateModel(
            name='ClassificationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('classifications_count', models.IntegerField(default=0)),
                ('total_time_seconds', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classification_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Classification Session',
                'verbose_name_plural': 'Classification Sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_classification', models.CharField(choices=[('scientific_results', 'Scientific Results'), ('meta_research', 'Meta-research'), ('not_sure', 'Not Sure')], max_length=50)),
                ('meta_aspects', models.JSONField(blank=True, default=list, help_text='List of meta-research aspect codes')),
                ('infrastructure', models.TextField(blank=True, help_text='Infrastructure or tools mentioned', max_length=500)),
                ('comments', models.TextField(blank=True)),
                ('time_spent_seconds', models.IntegerField(default=0)),
                ('is_training', models.BooleanField(default=False)),
                ('is_valid', models.BooleanField(default=True)),
                ('validation_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('abstract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='abstracts.abstract')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_classifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Classification',
                'verbose_name_plural': 'Classifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'abstract'], name='classificat_user_id_1c432e_idx'), models.Index(fields=['main_classification'], name='classificat_main_cl_07257b_idx'), models.Index(fields=['is_training'], name='classificat_is_trai_0c3773_idx'), models.Index(fields=['-created_at'], name='classificat_created_a42395_idx')],
                'unique_together': {('user', 'abstract')},
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('category_type', models.CharField(choices=[('main', 'Main Classification'), ('meta_aspect', 'Meta-research Aspect')], db_index=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('allows_multiple', models.BooleanField(default=False)),
                ('show_if_parent_values', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='classifications.category')),
                ('show_if_parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conditional_children', to='classifications.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['category_type', 'order', 'name'],
                'indexes': [models.Index(fields=['code'], name='classificat_code_276bf8_idx'), models.Index(fields=['category_type', 'is_active'], name='classificat_categor_c3ffe2_idx')],
            },
        ),
    ]
