# Generated by Django 4.2.7 on 2025-11-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='main_classification',
            field=models.CharField(db_index=True, help_text='Code of the main classification category', max_length=100),
        ),
    ]
