# Generated by Django 4.2.7 on 2025-11-12 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classifications', '0002_alter_classification_main_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who made the classification. Can be null if user is deleted but classifications are preserved.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_classifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
