# Generated by Django 4.2.7 on 2025-11-12 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abstracts', '0002_abstract_last_shown_at_abstract_publication_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classifications', '0003_allow_null_user_in_classification'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedAbstract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, help_text='Personal notes about this abstract')),
                ('tags', models.JSONField(blank=True, default=list, help_text='Personal tags/labels for organization')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('abstract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='abstracts.abstract')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_abstracts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Abstract',
                'verbose_name_plural': 'Saved Abstracts',
                'ordering': ['-saved_at'],
                'indexes': [models.Index(fields=['user', '-saved_at'], name='classificat_user_id_a12ebe_idx'), models.Index(fields=['abstract'], name='classificat_abstrac_5e15be_idx')],
                'unique_together': {('user', 'abstract')},
            },
        ),
    ]
