# Generated by Django 4.2.7 on 2025-11-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifications', '0004_add_saved_abstract_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=models.CharField(blank=True, default='', help_text="User's country (optional)", max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='institution',
            field=models.CharField(blank=True, default='', help_text="User's institution or affiliation (optional)", max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_profile_public',
            field=models.BooleanField(default=False, help_text='Whether to show profile in public leaderboards and stats'),
        ),
    ]
