# Generated by Django 4.2.7 on 2025-11-13 11:07

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('classifications', '0005_userprofile_country_userprofile_institution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=django_countries.fields.CountryField(blank=True, help_text="User's country (optional, ISO 3166)", max_length=2),
        ),
    ]
