# Generated by Django 4.2.7 on 2025-11-13 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abstracts', '0003_abstract_affiliations_abstract_research_areas_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classifications', '0006_alter_userprofile_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedAbstract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(help_text='Email address of the recipient', max_length=254)),
                ('message', models.TextField(blank=True, help_text='Personal message from sender')),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('email_sent_successfully', models.BooleanField(default=False)),
                ('abstract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_by_users', to='abstracts.abstract')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_abstracts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shared Abstract',
                'verbose_name_plural': 'Shared Abstracts',
                'ordering': ['-shared_at'],
                'indexes': [models.Index(fields=['user', '-shared_at'], name='classificat_user_id_f2da89_idx'), models.Index(fields=['abstract', '-shared_at'], name='classificat_abstrac_0bee43_idx')],
            },
        ),
    ]
