# Generated by Django 4.2.7 on 2025-11-13 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('abstracts', '0003_abstract_affiliations_abstract_research_areas_and_more'),
        ('classifications', '0007_sharedabstract'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractDebate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Brief title for this debate topic', max_length=255)),
                ('text', models.TextField(help_text='Initial post explaining the debate topic')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_closed', models.BooleanField(default=False, help_text="Closed debates don't accept new comments")),
                ('is_pinned', models.BooleanField(default=False, help_text='Pinned debates appear at the top')),
                ('views_count', models.IntegerField(default=0)),
                ('abstract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debates', to='abstracts.abstract')),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_debates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Abstract Debate',
                'verbose_name_plural': 'Abstract Debates',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DebateComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Comment text (max 2000 characters)', max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False, help_text="Soft delete: shows 'Comment deleted' instead of text")),
                ('likes_count', models.IntegerField(default=0, help_text='Number of likes (for future implementation)')),
                ('debate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='classifications.abstractdebate')),
                ('parent_comment', models.ForeignKey(blank=True, help_text='Parent comment if this is a reply', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='classifications.debatecomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debate_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Debate Comment',
                'verbose_name_plural': 'Debate Comments',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['debate', 'created_at'], name='classificat_debate__3a2357_idx'), models.Index(fields=['user', '-created_at'], name='classificat_user_id_5dd911_idx'), models.Index(fields=['parent_comment', 'created_at'], name='classificat_parent__d6d1e5_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='abstractdebate',
            index=models.Index(fields=['abstract', '-created_at'], name='classificat_abstrac_44d59c_idx'),
        ),
        migrations.AddIndex(
            model_name='abstractdebate',
            index=models.Index(fields=['initiator', '-created_at'], name='classificat_initiat_b96364_idx'),
        ),
        migrations.AddIndex(
            model_name='abstractdebate',
            index=models.Index(fields=['-is_pinned', '-created_at'], name='classificat_is_pinn_3e38e9_idx'),
        ),
    ]
