# Generated by Django 4.2.7 on 2025-11-13 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classifications', '0008_abstractdebate_debatecomment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstractdebate',
            name='title',
        ),
    ]
