# Generated by Django 4.2.7 on 2025-11-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifications', '0009_remove_abstractdebate_title'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='debatecomment',
            name='classificat_parent__d6d1e5_idx',
        ),
        migrations.RemoveField(
            model_name='debatecomment',
            name='parent_comment',
        ),
        migrations.AlterField(
            model_name='debatecomment',
            name='text',
            field=models.TextField(help_text='Comment text (max 350 characters)', max_length=350),
        ),
    ]
