# Generated by Django 4.2.7 on 2025-11-13 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classifications', '0010_remove_debatecomment_classificat_parent__d6d1e5_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('debate_comment', 'New comment on your debate'), ('debate_reply', 'Reply to your comment'), ('debate_mention', 'Mentioned in a comment')], db_index=True, max_length=50)),
                ('message', models.TextField(help_text='Notification message')),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(help_text='User who triggered this notification (e.g., who commented)', on_delete=django.db.models.deletion.CASCADE, related_name='triggered_notifications', to=settings.AUTH_USER_MODEL)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='classifications.debatecomment')),
                ('debate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='classifications.abstractdebate')),
                ('user', models.ForeignKey(help_text='User who receives this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='classificat_user_id_0a3852_idx'), models.Index(fields=['user', 'is_read'], name='classificat_user_id_8c5f3f_idx'), models.Index(fields=['notification_type', '-created_at'], name='classificat_notific_a5e8f9_idx')],
            },
        ),
    ]
