# Generated by Django 4.2.7 on 2025-11-15 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classifications', '0011_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedDebate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(help_text='Email address of the recipient', max_length=254)),
                ('message', models.TextField(blank=True, help_text='Personal message from sender')),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('email_sent_successfully', models.BooleanField(default=False)),
                ('debate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_by_users', to='classifications.abstractdebate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_debates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shared Debate',
                'verbose_name_plural': 'Shared Debates',
                'ordering': ['-shared_at'],
                'indexes': [models.Index(fields=['user', '-shared_at'], name='classificat_user_id_d5a46b_idx'), models.Index(fields=['debate', '-shared_at'], name='classificat_debate__3e8a20_idx')],
            },
        ),
    ]
