# Generated by Django 4.2.7 on 2025-11-15 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classifications', '0012_shareddebate'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedDebate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, help_text='Personal notes about this debate')),
                ('tags', models.JSONField(blank=True, default=list, help_text='Personal tags/labels for organization')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('debate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='classifications.abstractdebate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_debates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Debate',
                'verbose_name_plural': 'Saved Debates',
                'ordering': ['-saved_at'],
                'indexes': [models.Index(fields=['user', '-saved_at'], name='classificat_user_id_110df4_idx'), models.Index(fields=['debate'], name='classificat_debate__47560e_idx')],
                'unique_together': {('user', 'debate')},
            },
        ),
    ]
