# Generated by Django 4.2.7 on 2025-11-15 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classifications', '0013_saveddebate'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowedDebate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, help_text='Personal notes about this debate')),
                ('tags', models.JSONField(blank=True, default=list, help_text='Personal tags/labels for organization')),
                ('followed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('debate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_by_users', to='classifications.abstractdebate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_debates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Followed Debate',
                'verbose_name_plural': 'Followed Debates',
                'ordering': ['-followed_at'],
            },
        ),
        migrations.DeleteModel(
            name='SavedDebate',
        ),
        migrations.AddIndex(
            model_name='followeddebate',
            index=models.Index(fields=['user', '-followed_at'], name='classificat_user_id_a8e6bc_idx'),
        ),
        migrations.AddIndex(
            model_name='followeddebate',
            index=models.Index(fields=['debate'], name='classificat_debate__e279d0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='followeddebate',
            unique_together={('user', 'debate')},
        ),
    ]
