# Generated by Django 4.2.7 on 2025-11-15 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classifications', '0014_rename_saveddebate_to_followeddebate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followeddebate',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='followeddebate',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='followeddebate',
            name='updated_at',
        ),
    ]
