# Generated by Django 4.2.7 on 2025-11-15 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifications', '0015_remove_followeddebate_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, default='', help_text="User's first name (optional)", max_length=150),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(blank=True, default='', help_text="User's last name (optional)", max_length=150),
        ),
    ]
